---
- name: set {{ ansible_distribution }} {{ ansible_distribution_major_version }} variable
  set_fact:
    isms_su_group: wheel
    # U-03 계정잠금 임계값
    isms_template_files_pam_d:
      - temp: system-auth.{{ ansible_distribution }}{{ ansible_distribution_major_version }}.j2
        dest: /etc/pam.d/system-auth
      - temp: password-auth.{{ ansible_distribution }}{{ ansible_distribution_major_version }}.j2
        dest: /etc/pam.d/password-auth   
      - temp: su.{{ ansible_distribution }}{{ ansible_distribution_major_version }}.j2
        dest: /etc/pam.d/su
    isms_pam_d:
    # U-02
      - dest: "/etc/pam.d/password-auth-ac"
        regexp: "pam_cracklib.so"
        line: "password    requisite     pam_cracklib.so try_first_pass retry=3 type= minlen=11 ucredit=-1 dcredit=-1 ocredit=-1"
    # U-02
      - dest: "/etc/pam.d/system-auth-ac"
        regexp: "pam_cracklib.so"
        line: "password    requisite     pam_cracklib.so try_first_pass retry=3 type= minlen=11 ucredit=-1 dcredit=-1 ocredit=-1"
    # U-45
      - dest: "/etc/pam.d/su"
        regexp: "^#*auth *required *pam_wheel.so.*"
        line: "auth		required	pam_wheel.so group=wheel"
    # for teleport motd
      - dest: "/etc/pam.d/sshd"
        regexp: "motd.dynamic"
        line: "session    optional     pam_motd.so  motd=/run/motd.dynamic"
      - dest: "/etc/pam.d/sshd"
        regexp: "noupdate$"
        line: "session    optional     pam_motd.so noupdate"
