---
- name: U-18 check hosts.allow
  stat:
    path: /etc/hosts.allow
  register: hosts_allow
  when: ('slb' not in ansible_hostname) or ('rlb' not in ansible_hostname) or ('sproxy' not in ansible_hostname) or ('mirror' not in ansible_hostname) or ('sage' not in ansible_hostname) or ('mint' not in ansible_hostname)
  tags: hosts_allow

- name: U-18 copy hosts.allow hosts.deny
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: true
  with_items: "{{ tcp_wrapper }}"
  when: hosts_allow.stat.exists|bool
  ignore_errors: yes
  tags: hosts_allow

- name: U-18 copy hosts.allow hosts.deny - for Rocky8
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: true
  with_items: "{{ tcp_wrapper }}"
  ignore_errors: yes
  tags: hosts_allow
