---
- name: set {{ ansible_distribution }} {{ ansible_distribution_major_version }} variable
  set_fact:
    isms_su_group: sudo
    isms_pkg_list:
      - libpam-modules-bin
      - libpam-pwquality
      - libpwquality-tools
    isms_template_files_pam_d:
      - temp: common-auth.{{ ansible_distribution }}{{ ansible_distribution_major_version }}.j2
        dest: /etc/pam.d/common-auth
      - temp: common-account.{{ ansible_distribution }}{{ ansible_distribution_major_version }}.j2
        dest: /etc/pam.d/common-account
    isms_pam_d:
    # U-03 계정 잠금 임계값 설정
      - dest: "/etc/pam.d/common-password"
        regexp: "pam_pwquality.so"
        line: "password       requisite                       pam_pwquality.so retry=3"
    
    # U-03 remove nullok
      - dest: "/etc/pam.d/common-auth"
        regexp: "pam_unix.so"
        line: "auth	[success=1 default=ignore]	pam_unix.so"
    
    # U-45
      - dest: "/etc/pam.d/su"
        regexp: "^# *auth *required *pam_wheel.so.*"
        line: "auth             required        pam_wheel.so group=sudo"
      - dest: "/etc/pam.d/su"
        regexp: "^# *auth *sufficient *pam_wheel.so.*"
        line: "auth             sufficient      pam_wheel.so trust group=sudo"
    isms_pwquality:
    # U-02
      - regexp: "^#* *minlen.*"
        line: "minlen = 11"
      - regexp: "^#* *minclass.*"
        line: "minclass = 3"
      - regexp: "^#* *ocredit.*"
        line: "ocredit = -1"
      - regexp: "^#* *ucredit.*"
        line: "ucredit = -1"
      - regexp: "^#* *lcredit.*"
        line: "lcredit = -1"
      - regexp: "^#* *enforcing.*"
        line: "enforcing = 1"
  tags: always
